### ISSUE TITLE
可否提供一个Nginx配置文件的完整示例

### ISSUE THREAD

**Issue by charlesvhe** [evansun922/nginx-quic#2]
Hi Evan，

我在使用 chromium-80.0.3963.1 配置文件如下：
使用listen       443 ssl;时可以正常访问，
使用listen              443 quic reuseport  sndbuf=1048576 rcvbuf=1048576;时页面无法访问，
请问是不是我配置文件有问题，能否给个完整的nginx配置示例呀？
_____________________________________________
worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen       80;
        server_name  example.com;

        location / {
            root   /mnt/d/wsl/MaxiBiz;
            index  index.html index.htm;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

    }

    server {
        listen              443 quic reuseport  sndbuf=1048576 rcvbuf=1048576;
        server_name  example.com;

        ssl_certificate      /mnt/d/wsl/example_com.pem;
        ssl_certificate_key  /mnt/d/wsl/example_com.key;

        ssl_session_cache    shared:SSL:1m;
        ssl_session_timeout  5m;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers  on;

        location / {
            root   /mnt/d/wsl/MaxiBiz;
            index  index.html index.htm;
        }
    }
}
_____________________________________________

**Comment by evansun922** [comment]
server {
    listen              443 quic reuseport  sndbuf=1048576 rcvbuf=1048576;
    listen              443 ssl;
    server_name  example.com;

    ssl_certificate      /mnt/d/wsl/example_com.pem;
    ssl_certificate_key  /mnt/d/wsl/example_com.key;

    ssl_session_cache    shared:SSL:1m;
    ssl_session_timeout  5m;

    ssl_ciphers  HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers  on;

    add_header alt-svc "quic=\":443\"; ma=500; v=\"46,44,43,39\"";

    location / {
        root   /mnt/d/wsl/MaxiBiz;
        index  index.html index.htm;
    }
}
