### ISSUE TITLE
能否介绍下使用QUIC后的提升效果

### ISSUE THREAD

**Issue by smilebinbin** [evansun922/nginx-quic#3]

**Comment by takakawa** [comment]
同求，另外这个模块是否有在生产环境使用？

**Comment by evansun922** [comment]
[QUIC网络测试.xlsx](http://106.120.154.87/QUIC_net_test.xlsx)，这个网络测试是我们前期调研的时候，自己的一个测试结果，总体来说，在网络不好的情况下，quic相对于tcp+bbr无明显优势。

下面这个图，是实际生产环境中，对离线下载视频速度的统计，可以看出quic的效果要远远好于http2和http1。
 ![视频离线下载速度对比](http://106.120.154.87/quic_download.png)

总结来说， 毕竟quic是下一代http协议，解决了上一代版本一些问题（比如，避免队头阻塞的多路复用），在网络不错的情况下，其下载速度高于传统的http协议。

另外，对于这个模块是否在生产环境中使用的问题，可以用chrome浏览器看看搜狐视频，我们早已经在搜狐视频中大量使用这个项目了，这个项目是搜狐视频对于开源社区的一个小贡献。
