### ISSUE TITLE
log_level do not work

### ISSUE THREAD

**Issue by liusenzhen** [evansun922/nginx-quic#4]
hi,when i set error log_level in nginx.conf like this :
error_log  /data/proclog/log/error.log info;
but the quic info do not print to error.log

**Comment by evansun922** [comment]
Info of log level prints very little unless there is a serious error, you can compile a debug version of ningx-quic and set "error_log  logs/error.log  debug" to print more

**Comment by liusenzhen** [comment]
yes,Thank you very much! The problem has been solved
