### ISSUE TITLE
通过SrsQuic无法推流成功

### ISSUE THREAD

**Issue by flying1314** [evansun922/nginx-quic#5]
通过SrsQuic编译后的raw_h264_publisher推流到nginx失败，nginx采用的是提供的bin文件，没有自己编译，失败原因是提示协议不支持，协议列表是空的，这是什么原因呢？在CentOS6或7上面都是一样的错误

**Comment by evansun922** [comment]
nginx-quic和srsquic都使用的是标准版的quic协议，最近chromium项目的标准版本quic协议有比较大的调整， 所以建议你更新最新的chromium， 然后重新编译 nginx-quic和 srsquic，保证这两个使用的是同一个 chromium tag版本， 后续我们还会进行维护升级这块。

**Comment by flying1314** [comment]
chromium还没有编译，都是使用提供的编译好的库，只是先测试下效果，nginx用提供的bin文件，srsquic因为有提供librawquic.so，所以只是自己编译下生成raw_h264_publisher，链接的库是github上提供的，所以如果出现推流不成功，那就是github上提供的nginx的bin和librawquic.so的版本不匹配是吧，跟在什么系统没关系吧，我是在CentOS6或7上使用，自己编译chromium会比较麻烦，暂时还没去研究，只是想先验证下推流效果

**Comment by evansun922** [comment]
对的， librawquic.so和nginx-quic现在版本不匹配， 我们最近项目比较忙， librawquic.so的chromium的版本比较老，版本不一致， 你可以切换到以前的tag分支，编译一个nginx-quic
或者重新编译一个最新的  librawquic.so













在 2020-04-12 21:04:37，"flyboyxiang" <notifications@github.com> 写道：

chromium还没有编译，都是使用提供的编译好的库，只是先测试下效果，nginx用提供的bin文件，srsquic因为有提供librawquic.so，所以只是自己编译下生成raw_h264_publisher，链接的库是github上提供的，所以如果出现推流不成功，那就是github上提供的nginx的bin和librawquic.so的版本不匹配是吧，跟在什么系统没关系吧，我是在CentOS6或7上使用，自己编译chromium会比较麻烦，暂时还没去研究，只是想先验证下推流效果

**Comment by limjoe** [comment]
@flying1314 后来你跑通了么？

**Comment by n0099** [comment]
> @flying1314 后来你跑通了么？

Try out this official branch: https://www.nginx.com/blog/binary-packages-for-preview-nginx-quic-http3-implementation/
