### ISSUE TITLE
请求一份Nginx-quic的客户端demo的源码

### ISSUE THREAD

**Issue by hphuang164** [evansun922/nginx-quic#8]
您好！ 我最近在学习Nginx相关的实践项目,  请问您是否方便分享客户端demo， 即bequic_client的源代码给我一份呢？

**Comment by evansun922** [comment]
可以关注一下这个人的github， https://github.com/sonysuqin/BeQuic ， 这是我在搜狐的同事，客户端的工作他主要负责，不过他的项目一直没有更新，可能和我nginx-quic协议版本对不上了， 需要你自己更新，改一下代码。

**Comment by hphuang164** [comment]
好的   感谢！
